#!/usr/bin/env bash
#
# Создание udev-правила для переименования Wi-Fi интерфейса по ID_PATH (не по MAC).
# Привязка к физическому устройству - устойчива к смене MAC-адреса.
#
# Важно: правило содержит KERNEL!="*mon" - интерфейсы в режиме monitor (wifi0mon)
# не переименовываются, иначе wifi_setup не сможет переключать managed<->monitor.
#
# Использование:
#   sudo ./wifi-rename-link.sh <текущее_имя> <новое_имя>
#   sudo ./wifi-rename-link.sh wlx00c0cab6938b wifi0
#
# Требования: udevadm. Запуск от root.
#
set -e

UDEV_RULES_DIR="/etc/udev/rules.d"
# 85 - после 80-net-setup-link, чтобы наше правило не перезаписывалось
RULE_PREFIX="85-wifiaudit"

usage() {
  echo "Использование: $0 <текущее_имя> <новое_имя>"
  echo "  Пример: $0 wlx00c0cab6938b wifi0"
  echo "  Пример: $0 wlx00c0cab4ae2d wifi1"
  echo ""
  echo "Первый аргумент - ТЕКУЩЕЕ имя интерфейса (из ip link / iwconfig)."
  echo "Привязка по ID_PATH (физическое устройство), не по MAC."
  echo "KERNEL!=\"*mon\" - monitor-интерфейсы (wifi0mon) не переименовываются."
  echo "Имя: 1-15 символов, буквы, цифры, _, -."
  exit 1
}

[[ $# -eq 2 ]] || usage
IFACE="$1"
NEW_NAME="$2"

# Проверка имени
if ! [[ "$NEW_NAME" =~ ^[a-zA-Z0-9_-]{1,15}$ ]]; then
  echo "Ошибка: имя должно содержать 1-15 символов (буквы, цифры, _, -)." >&2
  exit 1
fi

# Нельзя переименовать в wlan0/eth0 - гонка с ядром
if [[ "$NEW_NAME" =~ ^(wlan|eth)[0-9]+$ ]]; then
  echo "Предупреждение: имена wlan0, eth0 и т.п. могут конфликтовать с ядром. Рекомендуется wifi0, wifi1 и т.д." >&2
fi

# Проверка root
[[ "$EUID" -eq 0 ]] || { echo "Запустите с sudo." >&2; exit 1; }

# Удаление старых правил (70-wifiaudit, systemd .link)
for f in /etc/udev/rules.d/70-wifiaudit-*.rules; do
  [[ -f "$f" ]] && rm -v "$f"
done 2>/dev/null || true
for f in /etc/systemd/network/10-wifi-*.link; do
  [[ -f "$f" ]] && rm -v "$f"
done 2>/dev/null || true

# Проверка существования интерфейса
if ! ip link show "$IFACE" &>/dev/null; then
  echo "Ошибка: интерфейс $IFACE не найден." >&2
  exit 1
fi

# Получить ID_PATH (устойчив к смене MAC)
get_id_path() {
  for sys_path in "/sys/class/net/$IFACE" "/sys/class/net/$IFACE/device"; do
    [[ -e "$sys_path" ]] || continue
    resolved=$(readlink -f "$sys_path")
    id_path=$(udevadm info -q property -p "$resolved" 2>/dev/null | grep -E '^ID_PATH=' | cut -d= -f2-)
    [[ -n "$id_path" ]] && echo "$id_path" && return 0
  done
  return 1
}

ID_PATH=$(get_id_path)
if [[ -z "$ID_PATH" ]]; then
  echo "Ошибка: ID_PATH для $IFACE не найден. Убедитесь, что /sys доступен." >&2
  exit 1
fi

# Суффикс для имени файла (безопасный)
FILE_SUFFIX=$(echo "$ID_PATH" | tr '/:' '_-' | head -c 40)
RULE_FILE="${UDEV_RULES_DIR}/${RULE_PREFIX}-${FILE_SUFFIX}.rules"

# KERNEL!="*mon" - не переименовывать monitor-интерфейсы (wifi0mon и т.п.)
cat > "$RULE_FILE" << EOF
# WiFi Audit: rename $IFACE -> $NEW_NAME by ID_PATH (not MAC)
# KERNEL!="*mon" - monitor interfaces (wifi0mon) stay as-is for mode switching
# Generated by wifi-rename-link.sh

# ACTION add|change - trigger по умолчанию шлёт change для существующих устройств
SUBSYSTEM=="net", ACTION=="add", ENV{ID_PATH}=="$ID_PATH", KERNEL!="*mon", NAME="$NEW_NAME"
SUBSYSTEM=="net", ACTION=="change", ENV{ID_PATH}=="$ID_PATH", KERNEL!="*mon", NAME="$NEW_NAME"
EOF

echo "Создан: $RULE_FILE"
echo "ID_PATH: $ID_PATH"
echo ""
echo "Применение изменений..."
udevadm control --reload-rules
ip link set "$IFACE" down
udevadm trigger --action=add --subsystem-match=net
ip link set "$NEW_NAME" up
echo ""
echo "Готово. $IFACE -> $NEW_NAME"
echo "При переключении в monitor создаётся ${NEW_NAME}mon, правило его не трогает."
